/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:45722d3a-df04-4401-8442-ce7b958d9bed",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_aCZovznpt",
    "aws_user_pools_web_client_id": "2pstcnlmh1oinjcaroh8a2g4ct",
    "oauth": {}
};


export default awsmobile;
