/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:45722d3a-df04-4401-8442-ce7b958d9bed",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_aCZovznpt",
    "aws_user_pools_web_client_id": "2pstcnlmh1oinjcaroh8a2g4ct",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://izupg2tewzdufpcff67itgseie.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-heybkbvhxjb2fnqvqzoqzm3roi"
};


export default awsmobile;
